// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout.qtpl:1
package templates

//line templates/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout.qtpl:1
func StreamRender(qw422016 *qt422016.Writer, content []byte) {
//line templates/layout.qtpl:1
	qw422016.N().S(`
<!doctype html>
<html lang="en" data-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.classless.min.css">
    <style>
      code {
        background-color: inherit !important;
        color: inherit !important;
      }
    </style>
  </head>
  <body>
    <main>
      `)
//line templates/layout.qtpl:17
	qw422016.N().Z(content)
//line templates/layout.qtpl:17
	qw422016.N().S(`
    </main>
  </body>
</html>
`)
//line templates/layout.qtpl:21
}

//line templates/layout.qtpl:21
func WriteRender(qq422016 qtio422016.Writer, content []byte) {
//line templates/layout.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout.qtpl:21
	StreamRender(qw422016, content)
//line templates/layout.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:21
}

//line templates/layout.qtpl:21
func Render(content []byte) string {
//line templates/layout.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout.qtpl:21
	WriteRender(qb422016, content)
//line templates/layout.qtpl:21
	qs422016 := string(qb422016.B)
//line templates/layout.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout.qtpl:21
	return qs422016
//line templates/layout.qtpl:21
}
